name: AbundaLaCaca
version: '${version}'
main: dev.gewooniraj.abundalacaca.AbundaLaCaca
api-version: '1.20'
author: GewoonIraj
description: A simple plugin written in Kotlin, made for AbundaLaCaca (a private survival server).
website: java.bumdawae.xyz
commands:
  recipes:
    description: Opens the Recipes Menu.
    usage: /<command>
    aliases: [r]
  jumpscare:
    description: No idea what this does...
    usage: /<command>
    aliases: [boo]